[package]
name = "jetson"
version = "0.3.0"
authors = ["David Herman <david.herman@gmail.com>"]
license = "BSD-2-Clause"
repository = "https://github.com/jetson-cli/jetson"
edition = "2018"

[features]
universal-docs = ["jetson-core/universal-docs"]
mock-network = ["mockito", "jetson-core/mock-network"]
jetson-dev = []
smoke-tests = []

[[bin]]
name = "shim"
path = "src/shim.rs"

[dependencies]
jetson-core = { path = "crates/jetson-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.37"
console = "0.6.1"
failure_derive = "0.1.1"
failure = "0.1.1"
jetson-fail = { path = "crates/jetson-fail" }
jetson-fail-derive = { path = "crates/jetson-fail-derive" }
reqwest = { version = "0.9.9", features = ["hyper-011"] }
semver = "0.9.0"
structopt = "0.2.14"
rand = "0.5"
cfg-if = "0.1"
mockito = { version = "0.14.0", optional = true }
test-support = { path = "crates/test-support" }
which = "2.0.1"

[dev-dependencies]
hamcrest2 = "0.2.3"
envoy = "0.1.3"

[workspace]
