[package]
name = "volta-migrate"
version = "0.1.0"
authors = ["Charles Pierce <cpierce.grad@gmail.com>"]
edition = "2018"

[features]
pnpm = ["volta-layout/pnpm", "volta-core/pnpm"]

[dependencies]
volta-core = { path = "../volta-core" }
volta-layout = { path = "../volta-layout" }
log = { version = "0.4", features = ["std"] }
tempfile = "3.0.2"
semver = { git = "https://github.com/mikrostew/semver", branch = "new-parser" }
serde_json = { version = "1.0.37", features = ["preserve_order"] }
serde = { version = "1.0.85", features = ["derive"] }
walkdir = "2.2.9"
