[package]
name = "volta-core"
version = "0.1.0"
authors = ["David Herman <david.herman@gmail.com>"]
edition = "2018"

[features]
mock-network = ["mockito"]
# The `cross-platform-docs` feature flag is used for generating API docs for
# multiple platforms in one build.
# See ci/publish-docs.yml for an example of how it's enabled.
# See volta-core::path for an example of where it's used.
cross-platform-docs = []

[dependencies]
term_size = "0.3.0"
indicatif = "0.9.0"
console = "0.6.1"
readext = "0.1.0"
serde_json = { version = "1.0.37", features = ["preserve_order"] }
serde = { version = "1.0.85", features = ["derive"] }
archive = { path = "../archive" }
failure = "0.1.1"
failure_derive = "0.1.1"
volta-fail = { path = "../volta-fail" }
volta-fail-derive = { path = "../volta-fail-derive" }
lazycell = "1.2.0"
lazy_static = "1.3.0"
semver = { git = "https://github.com/mikrostew/semver", branch = "new-parser" }
cmdline_words_parser = "0.0.2"
reqwest = { version = "0.9.9", features = ["hyper-011"] }
headers-011 = { path = "../headers-011" }
cfg-if = "0.1"
winfolder = "0.1"
tempfile = "3.0.2"
os_info = "1.1.0"
detect-indent = { git = "https://github.com/stefanpenner/detect-indent-rs", branch = "master" }
envoy = "0.1.3"
mockito = { version = "0.14.0", optional = true }
regex = "1.0.6"
dirs = "1.0.4"
sha-1 = "0.8.1"
hex = "0.3.2"
chrono = "0.4.6"
validate-npm-package-name = { path = "../validate-npm-package-name" }
textwrap = "0.11.0"
atty = "0.2"
log = { version = "0.4", features = ["std"] }
notion-layout = { path = "../notion-layout" }
ref_thread_local = "0.0.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.6.0"
